### ISSUE TITLE
Forcing Master Mode Active with the debug menu will break the plugin/dalamud

### ISSUE THREAD

**Issue by TheHeadpatCat** [TheHeadPatCat/WoLightning#5]
This issue is known and will be resolved as soon as the rework of the Webserver is complete

**Comment by ShibariSenshi** [comment]
Are they ANY fixes for this at all? Ive tried uninstalling, reinstalling and deleted the appdata and it still is in master mode so I can't access anything because I accidently clicked it ;-;  Thank you!

**Comment by TheHeadpatCat** [comment]
@ShibariSenshi 
Yes, the current workaround is to use the /wolfolder command to open the config folder - DISABLE the plugin, deleting all the files within the folder and then re-enabling it again.

The Plugin has a failsafe to safe all configs whenever you disable it, so it has to be disabled first whenever you want to actually make changes manually.
