### ISSUE TITLE
[Bug] -- Triggering Party Member Death Causes Game Crash

### ISSUE THREAD

**Issue by emotionallydamaged** [TheHeadPatCat/WoLightning#9]
**Describe the bug**

**To Reproduce**
1. Configure the Party member death setting based on the settings shown in the screenshot section below.
2. Have a party member die (you can test by having a party member use self destruct on blue mage).
3. See error

**Expected behavior**
When a party member dies, the trigger should cause the user's selected device to activate based on the settings.

**Actual behavior**
The game throws an error (see below) and crashes to desktop after pressing ok.

**Screenshots**
Image of the settings for the Party member death setting:
![image](https://github.com/user-attachments/assets/1c6ffd59-6e7a-4ee3-af68-3f384e416d18)

Image of the error message upon triggering the setting:
![image](https://github.com/user-attachments/assets/350b0229-9b01-48ee-b50b-0637f376d020)

**Version**
0.4.1.2

**Additional context**
None

**Comment by TheHeadpatCat** [comment]
Ah, i was sure i fixed this issue - seems something made it pop up again.
Will take a look into this as soon as possible!

**Comment by TheHeadpatCat** [comment]
Fixed in 0.4.1.3
Thanks for the report again!
